# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: support
# Comment to post on issues marked as support requests. Add a link
# to a support page, or set to `false` to disable
supportComment: This issue tracker is not for support requests. Please send a message to my [Telegram](https://t.me/mcpe_pc) to get help with OreAboveEndStone.
# Whether to close issues marked as support requests
close: true
# Whether to lock issues marked as support requests
lock: false
